spring:
  config:
    import:
      - optional:file:${ENV_PATH:.}/.env[.properties]
  application:
    name: spring-market
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        sql: DEBUG


jwt:
  secret: ${JWT_SECRET}
  expire_time: ${JWT_EXPIRE_TIME}