spring:
  config:
    import:
      - optional:file:${ENV_PATH:.}/.env[.properties]
  application:
    name: spring-market
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
