name: development-ci
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - name: grant permission to gradle
        run: chmod +x gradlew

      - name: touch .env family
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: Build and analyze
        run: ./gradlew build

      - name: Upload Gradle Report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: gradle-report
          path: build/reports